# Generated by Django 3.0.8 on 2020-07-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200715_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content1',
            field=models.TextField(default='', verbose_name='Content of Article(Next)'),
        ),
    ]
